# Generated by Django 5.2.5 on 2025-08-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_track_name'),
        ('trainee', '0002_trainee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='trackid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='track.track'),
            preserve_default=False,
        ),
    ]
