# Generated by Django 5.2.5 on 2025-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='Dina', max_length=50),
            preserve_default=False,
        ),
    ]
